Exception on /demo [POST]
Traceback (most recent call last):
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhirender/myprojects/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhirender/myprojects/week_10/custom-wake-word/app/views/main.py", line 60, in demo
    predictions=wake_word.detect_triggerword(file_path)[0,:,0]
  File "/home/dhirender/myprojects/week_10/custom-wake-word/ml_backend/predict.py", line 32, in detect_triggerword
    x = graph_spectrogram(filename)
  File "/home/dhirender/myprojects/week_10/custom-wake-word/ml_backend/td_utils.py", line 15, in graph_spectrogram
    pxx, freqs, bins, im = plt.specgram(data[:,0], nfft, fs, noverlap = noverlap)
NameError: name 'plt' is not defined
